# Generated by Django 4.2.3 on 2023-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_title_content_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='brief',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='brief',
            field=models.TextField(),
        ),
    ]
